### ISSUE TITLE
InvalidCapture("module")

### ISSUE THREAD

**Issue by dciug** [tree-sitter/tree-sitter-c-sharp#342] opened 2024-07-24 13:38 UTC
This line errors out when loading the TagsConfiguration: https://github.com/tree-sitter/tree-sitter-c-sharp/blob/31a64b28292aac6adf44071e449fa03fb80eaf4e/queries/tags.scm#L23

Version: 0.21.3

**Comment by amaanq** [comment] 2024-11-24 19:45
Should be fixed, can't reproduce now

**Closed by amaanq** 2024-11-24 19:45 UTC
